# Création d'un fichier unique avec les informations historiques (2015 à 2017) et théoriques

In [14]:
import pandas as pd
import numpy as np
import os
os.chdir("")

## Indication des fichiers qui vont être utilisés

In [15]:
file_origine='line_p.csv'
file_compare_verano='crono_verano_P.csv'
file_compare_invierno='crono_invierno_P.csv'

## Lecture des fichier et intégration dans des Dataframes

In [16]:
#Lecture du fichier origine et mise dans un dataframe
df_origine=pd.read_csv(file_origine,delimiter=';', low_memory=False)
#Affichage des 10 premières lignes du dataframe
df_origine.head(10)
#df_origine.shape

,FR1_FECHA,FR1_LINEA,FR1_TIPO,FR1_REGIST,FR1_ORDEN,FR1_TREN,FR1_CAUC1,FR1_CAUC2,FR1_COCC1,FR1_COCC2,FR1_KM,FR1_KMV,FR1_VIAC1,FR1_VIAC2,FR1_SALC1,FR1_SALC2,FR1_SCAUC2,FR1_SCAUC1
0,01/01/2015,P,F,1,1,1,V,,1,0,0,0,N,N,07:05:00,00:00:00,,FALTA DE CUSTODIA POLICIAL
1,01/01/2015,P,F,2,2,1,V,,1,0,0,0,N,N,08:00:00,00:00:00,,FALTA DE CUSTODIA POLICIAL
2,01/01/2015,P,F,3,3,2,V,,1,0,0,0,N,N,08:09:40,00:00:00,,FALTA DE CUSTODIA POLICIAL
3,01/01/2015,P,F,4,4,3,V,,1,0,0,0,N,N,08:19:20,00:00:00,,FALTA DE CUSTODIA POLICIAL
4,01/01/2015,P,F,5,5,4,V,,1,0,0,0,N,N,08:29:00,00:00:00,,FALTA DE CUSTODIA POLICIAL
5,01/01/2015,P,F,6,6,5,V,,1,0,0,0,N,N,08:38:40,00:00:00,,FALTA DE CUSTODIA POLICIAL
6,01/01/2015,P,F,7,7,6,V,,1,0,0,0,N,N,08:48:20,00:00:00,,FALTA DE CUSTODIA POLICIAL
7,01/01/2015,P,F,8,8,1,V,,1,0,0,0,N,N,08:58:00,00:00:00,,FALTA DE CUSTODIA POLICIAL
8,01/01/2015,P,F,10,10,3,V,,1,0,0,0,N,N,09:17:20,00:00:00,,FALTA DE CUSTODIA POLICIAL
9,01/01/2015,P,F,11,11,4,V,,1,0,0,0,N,N,09:27:00,00:00:00,,FALTA DE CUSTODIA POLICIAL

In [17]:
#Lecture du 1er fichier comparaison et mise dans un dataframe
df_compare_verano=pd.read_csv(file_compare_verano,delimiter=';', low_memory=False)
#Affichage des 10 premières lignes du dataframe
df_compare_verano.head(10)
#df_compare_verano.shape

,PERIODO,LINEA,TIPO_DIA,ORDEN,TREN,SAL_C1,SAL_C2,INT_C1,INT_C2,FORM,OBSERVACIONES
0,2015,P,HABIL,1,1,SALIDA ADELANTADA,SALIDA ADELANTADA,NaN,NaN,1,NaN
1,2015,P,HABIL,2,1,05:30:00,SALIDA ADELANTADA,NaN,NaN,1,NaN
2,2015,P,HABIL,3,2,05:37:15,07:15:00,00:07:15,NaN,1,NaN
3,2015,P,HABIL,4,3,05:44:30,07:15:00,00:07:15,NaN,1,NaN
4,2015,P,HABIL,5,4,05:51:45,07:15:00,00:07:15,NaN,1,NaN
5,2015,P,HABIL,6,5,05:59:00,07:15:00,00:07:15,NaN,1,NaN
6,2015,P,HABIL,7,6,06:06:15,07:15:00,00:07:15,NaN,1,NaN
7,2015,P,HABIL,8,7,06:13:30,07:15:00,00:07:15,NaN,1,NaN
8,2015,P,HABIL,9,8,06:20:45,07:15:00,00:07:15,NaN,1,NaN
9,2015,P,HABIL,10,1,06:28:00,07:15:00,00:07:15,NaN,1,NaN

In [18]:
#Lecture du 2ème fichier comparaison et mise dans un dataframe
df_compare_invierno=pd.read_csv(file_compare_verano,delimiter=';', low_memory=False)
#Affichage des 10 premières lignes du dataframe
df_compare_invierno.head(10)
#df_compare_invierno.shape

,PERIODO,LINEA,TIPO_DIA,ORDEN,TREN,SAL_C1,SAL_C2,INT_C1,INT_C2,FORM,OBSERVACIONES
0,2015,P,HABIL,1,1,SALIDA ADELANTADA,SALIDA ADELANTADA,NaN,NaN,1,NaN
1,2015,P,HABIL,2,1,05:30:00,SALIDA ADELANTADA,NaN,NaN,1,NaN
2,2015,P,HABIL,3,2,05:37:15,07:15:00,00:07:15,NaN,1,NaN
3,2015,P,HABIL,4,3,05:44:30,07:15:00,00:07:15,NaN,1,NaN
4,2015,P,HABIL,5,4,05:51:45,07:15:00,00:07:15,NaN,1,NaN
5,2015,P,HABIL,6,5,05:59:00,07:15:00,00:07:15,NaN,1,NaN
6,2015,P,HABIL,7,6,06:06:15,07:15:00,00:07:15,NaN,1,NaN
7,2015,P,HABIL,8,7,06:13:30,07:15:00,00:07:15,NaN,1,NaN
8,2015,P,HABIL,9,8,06:20:45,07:15:00,00:07:15,NaN,1,NaN
9,2015,P,HABIL,10,1,06:28:00,07:15:00,00:07:15,NaN,1,NaN

## Concaténation des deux fichiers de comparaison des horaires théoriques

In [1]:
df_compare_invierno['SAISON']='INVIERNO'
df_compare_verano['SAISON']='VERANO'

#concaténation des 2 fichiers de comparaison
df_compare=pd.concat([df_compare_invierno,df_compare_verano],ignore_index=True)

#renommage de la colonne ORDEN pour effectuer le merge
df_compare=df_compare.rename(columns={'ORDEN':'FR1_REGIST'})

df_compare.head(10)
#df_compare.shape

NameError: name 'df_compare_invierno' is not defined

## Classement des fichiers selon la date et les numéros d'ordre (REGIST)

In [20]:
#trier le dataframe en fonction de 'FR1_FECHA' et 'FR1_REGIST'
df_origine=df_origine.sort_values(by=['FR1_FECHA','FR1_REGIST'])

## Rajout d'une colonne indiquant le type de jour

In [21]:
#Rajout d'une colonne indiquant le type de jour
df_origine['TIPO_DIA']=np.where(df_origine['FR1_TIPO']=='F','DOMINGO',
                               np.where(df_origine['FR1_TIPO']=='D','DOMINGO',
                                        np.where(df_origine['FR1_TIPO']=='S','SABADO',
                                                 np.where(df_origine['FR1_TIPO']=='H','HABIL','AUTRE'))))
#Affichage des 10 premières lignes du dataframe
#Compter les autres
pd.value_counts(df_origine['TIPO_DIA'].values, sort=False)
#df_origine.head(10)

HABIL      98040
DOMINGO    18101
SABADO     16854
dtype: int64

## Modification du type des colonnes contenant des dates au format date

In [22]:
from datetime import date, datetime

df_origine['FR1_FECHA'] = pd.to_datetime(df_origine['FR1_FECHA'], format="%d/%m/%Y")
df_origine.dtypes

FR1_FECHA     datetime64[ns]
FR1_LINEA             object
FR1_TIPO              object
FR1_REGIST             int64
FR1_ORDEN              int64
FR1_TREN               int64
FR1_CAUC1             object
FR1_CAUC2             object
FR1_COCC1              int64
FR1_COCC2              int64
FR1_KM                object
FR1_KMV                int64
FR1_VIAC1             object
FR1_VIAC2             object
FR1_SALC1             object
FR1_SALC2             object
FR1_SCAUC2            object
FR1_SCAUC1            object
TIPO_DIA              object
dtype: object

## Rajout d'une colonne indiquant le type de saison (VERANO ou INVIERNO)

In [23]:
from datetime import date, datetime
date1=datetime(2015,1,1,0,0,0)
date2=datetime(2015,3,1,0,0,0)
date3=datetime(2015,12,23,0,0,0)
date4=datetime(2016,3,1,0,0,0)
date5=datetime(2016,12,23,0,0,0)
date6=datetime(2017,3,1,0,0,0)
date7=datetime(2017,12,23,0,0,0)
date8=datetime(2018,3,1,0,0,0)

df_origine['SAISON']=np.where(np.logical_and(df_origine['FR1_FECHA']>=date1,df_origine['FR1_FECHA']<date2),'VERANO',
                              np.where(np.logical_and(df_origine['FR1_FECHA']>=date2,df_origine['FR1_FECHA']<date3),'INVIERNO',
                                       np.where(np.logical_and(df_origine['FR1_FECHA']>=date3,df_origine['FR1_FECHA']<date4),'VERANO',
                                                np.where(np.logical_and(df_origine['FR1_FECHA']>=date4,df_origine['FR1_FECHA']<date5),'INVIERNO',
                                                         np.where(np.logical_and(df_origine['FR1_FECHA']>=date5,df_origine['FR1_FECHA']<date6),'VERANO',
                                                                  np.where(np.logical_and(df_origine['FR1_FECHA']>=date6,df_origine['FR1_FECHA']<date7),'INVIERNO',
                                                                           np.where(np.logical_and(df_origine['FR1_FECHA']>=date7,df_origine['FR1_FECHA']<date8),'VERANO','AUTRE')))))))

#Vérifier inversion mois/jour
df_origine.head(10)

,FR1_FECHA,FR1_LINEA,FR1_TIPO,FR1_REGIST,FR1_ORDEN,FR1_TREN,FR1_CAUC1,FR1_CAUC2,FR1_COCC1,FR1_COCC2,FR1_KM,FR1_KMV,FR1_VIAC1,FR1_VIAC2,FR1_SALC1,FR1_SALC2,FR1_SCAUC2,FR1_SCAUC1,TIPO_DIA,SAISON
0,2015-01-01,P,F,1,1,1,V,,1,0,0,0,N,N,07:05:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
1,2015-01-01,P,F,2,2,1,V,,1,0,0,0,N,N,08:00:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
2,2015-01-01,P,F,3,3,2,V,,1,0,0,0,N,N,08:09:40,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
3,2015-01-01,P,F,4,4,3,V,,1,0,0,0,N,N,08:19:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
4,2015-01-01,P,F,5,5,4,V,,1,0,0,0,N,N,08:29:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
5,2015-01-01,P,F,6,6,5,V,,1,0,0,0,N,N,08:38:40,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
6,2015-01-01,P,F,7,7,6,V,,1,0,0,0,N,N,08:48:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
7,2015-01-01,P,F,8,8,1,V,,1,0,0,0,N,N,08:58:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO
65,2015-01-01,P,F,9,9,2,,,1,0,"14,8",0,S,N,09:05:40,00:00:00,,,DOMINGO,VERANO
8,2015-01-01,P,F,10,10,3,V,,1,0,0,0,N,N,09:17:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO

## Ajout d'une colonne indiquant l'année en question (en ftc de la date)

In [24]:
df_origine['PERIODO']=df_origine['FR1_FECHA'].dt.year
#df_origine.shape
df_origine.head(10)

,FR1_FECHA,FR1_LINEA,FR1_TIPO,FR1_REGIST,FR1_ORDEN,FR1_TREN,FR1_CAUC1,FR1_CAUC2,FR1_COCC1,FR1_COCC2,...,FR1_KMV,FR1_VIAC1,FR1_VIAC2,FR1_SALC1,FR1_SALC2,FR1_SCAUC2,FR1_SCAUC1,TIPO_DIA,SAISON,PERIODO
0,2015-01-01,P,F,1,1,1,V,,1,0,...,0,N,N,07:05:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
1,2015-01-01,P,F,2,2,1,V,,1,0,...,0,N,N,08:00:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
2,2015-01-01,P,F,3,3,2,V,,1,0,...,0,N,N,08:09:40,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
3,2015-01-01,P,F,4,4,3,V,,1,0,...,0,N,N,08:19:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
4,2015-01-01,P,F,5,5,4,V,,1,0,...,0,N,N,08:29:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
5,2015-01-01,P,F,6,6,5,V,,1,0,...,0,N,N,08:38:40,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
6,2015-01-01,P,F,7,7,6,V,,1,0,...,0,N,N,08:48:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
7,2015-01-01,P,F,8,8,1,V,,1,0,...,0,N,N,08:58:00,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015
65,2015-01-01,P,F,9,9,2,,,1,0,...,0,S,N,09:05:40,00:00:00,,,DOMINGO,VERANO,2015
8,2015-01-01,P,F,10,10,3,V,,1,0,...,0,N,N,09:17:20,00:00:00,,FALTA DE CUSTODIA POLICIAL,DOMINGO,VERANO,2015

## Merge des 2 fichiers avec les colonnes SAISON, PERIODO, TIPO_DIA et FR1_REGIST

In [25]:
df_final=pd.merge(df_origine,df_compare,on=['SAISON','PERIODO','TIPO_DIA','FR1_REGIST'],how='left')
df_final=df_final.sort_values(by=['FR1_FECHA','FR1_REGIST'])
df_final.shape

(132995, 29)

## Export des données sous CSV

In [26]:
export_tot='BA_' + df_final.iloc[1,1] + '_donnees_preparees.csv'
print(export_tot)
df_final.to_csv(export_tot,sep=';',index=False)

BA_P_donnees_preparees.csv